### ISSUE TITLE
Dashboard not getting updated

### ISSUE THREAD

**Issue by venurgopal** [mysteriumnetwork/feedback#10]
Hi ,

My nodes are running for 4 days now, but my dashboard is not showing the 'Quality' and 'Last Seen' values. When I checked for my nodes in the discovery URL, they show the values. The problem is only with the UI.

![image](https://user-images.githubusercontent.com/41584575/224138765-320b8dd1-6d1d-4828-951f-546f620d3161.png)

My email is venugopal.r@gmail.com

Thanks
 Venu

**Comment by Guillembonet** [comment]
not relevant to this repo
