### ISSUE TITLE
Update to latest intercom api version

### ISSUE THREAD

**Issue by Guillembonet** [mysteriumnetwork/feedback#7]
It looks like it is possible to use the latest version using `contacts/search` by `external_id` to update users.

**Comment by Guillembonet** [comment]
Tried this, and I guess it can maybe work but it seems to get much more complex. It is also subject to weird restrictions (like updating a lead requires an email, or that it requires more API calls than before) which would affect us negatively without offering any benefit. Furthermore, the golang library for intercom is not updated (now is for 1.3) and lacks functionality. I don't think updating is worth it since v1.4 is still supported fully with no plans of deprecation.

**Comment by Ayse-AK** [comment]
Thank you Guillem, I'll remove this from the node happiness board
